export const GET_ALL_CHARACTERS_START = "GET_ALL_CHARACTERS_START";
export const GET_ALL_CHARACTERS_SUCCESS = "GET_ALL_CHARACTERS_SUCCESS";
export const GET_ALL_CHARACTERS_FAIL = "GET_ALL_CHARACTERS_FAIL";
